server:
  host: localhost
  port: 8080

spring:
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: create
      format_sql : true

  datasource:
    url: jdbc:mysql://localhost:3306/my_page?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jongha_page
    password: Whdgk13579!


logging:
  level:
    org:
      springframework: debug
      web: debug
